### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by gjbunyea** [enlightencmu/capstone#1]
I don't own this repo, so can the admin go into Settings and find "Enforce HTTPS" -> click the checkmark and should be good to go!

![image](https://user-images.githubusercontent.com/18299544/58718339-4f975c80-839b-11e9-9475-6d3180c16dd0.png)

**Comment by pol-chen** [comment]
DONE ;-)

[https://enlighten.education](https://enlighten.education) is available now.
